name: 'main_dbt_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'main_dbt_project'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  main_dbt_project:
    +materialized: view
    # Staging модели всегда создаются в схеме stage
    staging:
      +materialized: table
    # RDV модели - удаляем таблицы перед созданием для PRIMARY таблиц
    # Используем локальные pre_hook в конфигурации каждой модели
    # Не используем глобальный pre-hook, так как модели имеют свои локальные pre_hook
    rzdm_rdv:
      # Локальные pre_hook в моделях используют прямой SQL: DROP TABLE IF EXISTS {{ this }} FORCE
    # BDV модели - большинство создаются как VIEW,
    # поэтому pre-hook не нужен (VIEW можно пересоздавать напрямую)
    # Для TABLE моделей в BDV используется явное указание materialized='table'
    # с локальным pre_hook в конфигурации модели
    rzdm_bdv:
      # Не используем глобальный pre-hook для BDV, так как:
      # 1. VIEW модели можно пересоздавать напрямую без удаления
      # 2. TABLE модели имеют свой локальный pre_hook в config
    # MART модели - dims это VIEW, facts это TABLE
    rzdm_mart:
      dims:
        # VIEW модели не нуждаются в pre-hook
      facts:
        # TABLE модели нуждаются в pre-hook
        # Используем прямой SQL вместо макроса, чтобы избежать проблем с подключением
        +pre-hook: "DROP TABLE IF EXISTS {{ this }} FORCE"
    # REPORT модели - все VIEW, pre-hook не нужен
    rzdm_report:
      # VIEW модели можно пересоздавать напрямую без удаления
      

# Глобальная конфигурация тестов - все тесты будут предупреждениями
# Это предотвратит падение пайплайна при ошибках в тестах
tests:
  main_dbt_project:
    +severity: warn  # Все тесты будут предупреждениями, а не ошибками


